//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationDetail
    {
        public string RoomID { get; set; }
        public string GuestID { get; set; }
        public string ServiceName { get; set; }
        public double ServicePrice { get; set; }
        public string ServiceID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual Room Room { get; set; }
        public virtual Service Service { get; set; }
    }
}
